### ISSUE TITLE
openpool.net is down

### ISSUE THREAD

**Issue by downrightmike** [henrikssn/OpenPool#1]
Hello,
I went to check out your site on openpool.net and it is down with a filler page from the host wpengine to contact them. Just a heads up.

Mike

**Comment by henrikssn** [comment]
Hi!

Yeah, the domain is dead.. I haven't had time nor financials to have it up. I guess someone else took it then. You are very free to spawn the project at another domain :)

Thanks for noticing!

Erik

**Comment by YudinV** [comment]
Hi! I know a free hosting (http://www.hostinger.com.ua/)
But they dont have  english web-site.
If you need i can help with registration

**Comment by henrikssn** [comment]
@Pokrof You are welcome to set up a demo website there, however I have not time to maintain that right now. If you make any improvements to the code base I'll be happy to pull these in.
